apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-flower
  name: celery-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-flower
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-flower
    spec:
      containers:
      - env:
        - name: AMQP_ADMIN_HOST
          value: rabbitmq
        - name: AMQP_ADMIN_PASSWORD
          value: bitnami
        - name: AMQP_ADMIN_PORT
          value: "15672"
        - name: AMQP_ADMIN_USERNAME
          value: user
        - name: AMQP_HOST
          value: rabbitmq
        - name: AMQP_PASSWORD
          value: bitnami
        - name: AMQP_PORT
          value: "5672"
        - name: AMQP_USERNAME
          value: user
        - name: FLOWER_BASIC_AUTH
          value: user:test
        image: gregsi/latest-celery-flower-docker:latest
        imagePullPolicy: ""
        name: celery-flower
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
